services:
  postgres:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_USER: threadbox_api
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - /opt/postgres/pg_hba.conf:/pg_hba.conf:ro
    command: postgres -c hba_file=/pg_hba.conf
    networks:
      - threadbox
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx-locations.conf:/etc/nginx/includes/locations.conf:ro
      - /etc/ssl/certs/raspberrypi.local_fullchain.crt:/certs/raspberrypi.local_fullchain.crt:ro
      - /etc/ssl/private/raspberrypi.local.key:/certs/raspberrypi.local.key:ro
      - /var/www/threadbox-front:/var/www/threadbox-front:ro
    networks:
      - threadbox
volumes:
  pgdata:
networks:
  threadbox:
    external: true
    name: threadbox-network