services:
  postgres:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_USER: threadbox_api
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - /opt/postgres/pg_hba.conf:/pg_hba.conf:ro
    command: postgres -c hba_file=/pg_hba.conf
    networks:
      - threadbox
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:8080:8080"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - /etc/ssl/certs/thread-box.com.crt:/certs/thread-box.com.crt:ro
      - /etc/ssl/private/thread-box.com.key:/certs/thread-box.com.key:ro
      - /etc/ssl/certs/app.thread-box.com.crt:/certs/app.thread-box.com.crt:ro
      - /etc/ssl/private/app.thread-box.com.key:/certs/app.thread-box.com.key:ro
      - /etc/ssl/certs/api.thread-box.com.crt:/certs/api.thread-box.com.crt:ro
      - /etc/ssl/private/api.thread-box.com.key:/certs/api.thread-box.com.key:ro
      - /var/www/threadbox-front:/var/www/threadbox-front:ro
    networks:
      - threadbox
volumes:
  pgdata:
networks:
  threadbox:
    external: true
    name: threadbox-network