server {
    listen 80 default_server;
    server_name _;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl default_server;
    server_name _;

    ssl_certificate /certs/raspberrypi.local_fullchain.crt;
    ssl_certificate_key /certs/raspberrypi.local.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    include /etc/nginx/includes/locations.conf;
}

server {
    listen 127.0.0.1:8080;
    server_name localhost;

    include /etc/nginx/includes/locations.conf;
}
