server {
    listen 80;
    server_name app.thread-box.com;

    return 301 https://$host$request_uri;
}

server {
    listen 8080;
    server_name app.thread-box.com;

    include /etc/nginx/conf.d/snippets/app.conf;
}

server {
    listen 443 ssl;
    server_name app.thread-box.com;

    ssl_certificate /certs/app.thread-box.com.crt;
    ssl_certificate_key /certs/app.thread-box.com.key;
    include /etc/nginx/conf.d/snippets/ssl.conf;
    include /etc/nginx/conf.d/snippets/app.conf;
}
