server {
    listen 80 default_server;
    listen 8080 default_server;
    server_name _;
    return 404;
}

server {
    listen 443 ssl default_server;
    server_name _;

    ssl_certificate /certs/thread-box.com.crt;
    ssl_certificate_key /certs/thread-box.com.key;
    include /etc/nginx/conf.d/snippets/ssl.conf;

    return 404;
}
