name: Release
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Extracting SSL certificate
      env:
        SSL_PFX_BASE64: ${{ secrets.SSL_PFX_BASE64 }}
        SSL_PASSWORD: ${{ secrets.SSL_PASSWORD }}
      run: |
        set -euxo pipefail
        rm -rf certs
        mkdir -p certs
        printf "%s" "$SSL_PFX_BASE64" | base64 -d > certs/cert.pfx

        file certs/cert.pfx
        openssl pkcs12 -info -in certs/cert.pfx -passin pass:"$SSL_PASSWORD"
        ls -lh certs/cert.pfx
        hexdump -C certs/cert.pfx | head -n 5

        openssl pkcs12 -in certs/cert.pfx -nocerts -nodes \
          -out certs/cert.key \
          -passin pass:"$SSL_PASSWORD"

        openssl pkcs12 -in certs/cert.pfx -clcerts -nokeys \
          -out certs/cert.crt \
          -passin pass:"$SSL_PASSWORD"

        chmod 600 certs/cert.pfx
        chmod 600 certs/cert.key
        chmod 600 certs/cert.crt
    - name: Docker
      run: |
        set -euxo pipefail
        docker compose up -d --build
        echo "Running containers:"
        docker ps
        echo "nginx logs:"
        docker logs nginx || true
        echo "threadbox-api logs:"
        docker logs threadbox-api || true
      env:
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        CONNECTION_STRINGS__DATABASE: ${{ secrets.CONNECTION_STRINGS__DATABASE }}
        DEFAULT_ADMIN_CREDENTIALS__PASSWORD: ${{ secrets.DEFAULT_ADMIN_CREDENTIALS__PASSWORD }}
        OIDC_BFF_CLIENT_SECRET: ${{ secrets.OIDC_BFF_CLIENT_SECRET }}
        SSL_PASSWORD: ${{ secrets.SSL_PASSWORD }}
