name: Release
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ThreadboxApi
    env:
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      CONNECTION_STRINGS__POSTGRES: ${{ secrets.CONNECTION_STRINGS__POSTGRES }}
      DEFAULT_ADMIN_CREDENTIALS__PASSWORD: ${{ secrets.DEFAULT_ADMIN_CREDENTIALS__PASSWORD }}
      OIDC_BFF_CLIENT_SECRET: ${{ secrets.OIDC_BFF_CLIENT_SECRET }}
      PFX_PASSWORD: ${{ secrets.PFX_PASSWORD }}
    steps:
    - uses: actions/checkout@v3
    - name: Clean containers
      run: |
        set -euo pipefail
        docker compose down || true
    - name: Deploy (CI - no restart policy)
      run: |
        docker compose -f docker-compose.yml -f docker-compose.ci.yml up -d --build --wait || true
    - name: Check containers status
      run: |
        set -euo pipefail
        
        echo "================ CONTAINERS ================"
        docker compose ps
        
        FAILED=0
        
        for SERVICE in $(docker compose config --services); do
          CONTAINER=$(docker compose ps -q $SERVICE)
          
          echo
          echo "================ Checking $SERVICE ================"
          
          if [ -z "$CONTAINER" ]; then
            echo "Container for $SERVICE not found"
            echo
            echo "---------------- Logs for $SERVICE ----------------"
            docker compose logs $SERVICE --tail=200 || true
            FAILED=1
            continue
          fi

          STATUS=$(docker inspect -f '{{.State.Status}}' "$CONTAINER")
          EXIT_CODE=$(docker inspect -f '{{.State.ExitCode}}' "$CONTAINER")
          
          echo "Status: $STATUS"
          echo "Exit code: $EXIT_CODE"
          
          echo "---------------- Logs for $SERVICE ----------------"
          docker logs "$CONTAINER" --tail=200 || true
          
          if [[ $STATUS != "running" || "$EXIT_CODE" -ne 0 ]]; then
            echo "$SERVICE is unhealthy"
            FAILED=1
          fi
        done
        
        if [ "$FAILED" -ne 0 ]; then
          echo
          echo "One or more containers failed."
          exit 1
        fi
        
        echo
        echo "Deploy completed successfully."
    - name: Deploy with restart policy
      run: |
        set -euo pipefail
        docker compose down
        docker compose up -d --build
