name: Seeding
on:
  workflow_dispatch:
jobs:
  seed:
    runs-on: self-hosted
    env:
      DOTNET_ROOT: /home/pi/.dotnet
      ConnectionStrings__Postgres: ${{ secrets.CONNECTION_STRINGS__POSTGRES }}
      DefaultAdminCredentials__Username: ${{ secrets.DEFAULT_ADMIN_CREDENTIALS__USERNAME }}
      DefaultAdminCredentials__Password: ${{ secrets.DEFAULT_ADMIN_CREDENTIALS__PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Add dotnet to PATH
        run: echo "$HOME/.dotnet:$PATH" >> $GITHUB_PATH
      - name: Run seeding
        working-directory: Seeding
        run: dotnet run -c Release --no-launch-profile
